export default [
  ["Best White Common", null, "/trophies/white1.png"],
  ["Best Blue Common", null, "/trophies/blue1.png"],
  ["Best Black Common", null, "/trophies/black1.png"],
  ["Best Red Common", null, "/trophies/red1.png"],
  ["Best Green Common", null, "/trophies/green1.png"],
  ["Best White Uncommon", null, "/trophies/white1.png"],
  ["Best Blue Uncommon", null, "/trophies/blue1.png"],
  ["Best Black Uncommon", null, "/trophies/black1.png"],
  ["Best Red Uncommon", null, "/trophies/red1.png"],
  ["Best Green Uncommon", null, "/trophies/green1.png"],
  ["Best Common", null, "/trophies/todo.png"],
  ["Best Uncommon", null, "/trophies/todo.png"],
  ["Best Rare", null, "/trophies/todo.png"],
  ["Best Mythic", null, "/trophies/todo.png"],
  ["Best Build-Around", null, "/trophies/todo.png"],
  ["Best Signpost Uncommon", null, "/trophies/todo.png"],
  ["Best Art", null, "/trophies/todo.png"],
  ["Biggest Noob Trap", null, "/trophies/todo.png"],
  ["Worst Card In The Set", null, "/trophies/todo.png"],
  ["Biggest Bomb", null, "/trophies/todo.png"],
  ["Most Important Glue For Its Archetype", null, "/trophies/todo.png"],
  ["Coolest Design", null, "/trophies/todo.png"]
]